[build]
  # Comando para construir tu proyecto (Vite)
  command = "npm run build"
  # Carpeta que Netlify debe publicar
  publish = "dist"

[functions]
  # Carpeta donde est√°n tus funciones serverless
  directory = "netlify/functions"
